package admin

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
    "cmp"
    "context"
    "slices"
    "strconv"
    "time"

    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/packages/go-server-kit/modules/auth"
    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/packages/go-server-kit/transport/httperr"
    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/projects/multi-database-demo/internal/graph/model"
    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/projects/multi-database-demo/internal/graph/scalar"
    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/projects/multi-database-demo/internal/service"
)

// CreateUser 映射创建输入并调用认证服务，按 Schema 约定返回单元素用户列表。
func (r *mutationResolver) CreateUser(ctx context.Context, set CreateUserSetInput) ([]*UserItem, error) {
    if err := r.usersReady(); err != nil {
        return nil, err
    }

    row, err := r.Users.CreateUser(ctx, auth.CreateUserInput{
        Name:     set.Name,
        Email:    set.Email,
        Password: set.Password,
        Role:     set.Role,
    })
    if err != nil {
        return nil, err
    }
    return []*UserItem{fromUser(row)}, nil
}

// UpdateUser 保留省略与显式清空语义，将筛选批量更新结果映射为用户 DTO。
func (r *mutationResolver) UpdateUser(ctx context.Context, set UpdateUserSetInput, where UserFilters) ([]*UserItem, error) {
    if err := r.usersReady(); err != nil {
        return nil, err
    }

    input := auth.UpdateUserInput{
        Name:       set.Name,
        Role:       set.Role,
        Banned:     set.Banned,
        BanReason:  auth.Optional[string]{Set: set.BanReason.IsSet(), Value: set.BanReason.Value()},
        BanExpires: auth.Optional[time.Time]{Set: set.BanExpires.IsSet()},
    }
    if value := set.BanExpires.Value(); value != nil {
        expires := time.Time(*value)
        input.BanExpires.Value = &expires
    }

    rows, err := r.Users.UpdateUsers(ctx, userFilters(&where), input)
    if err != nil {
        return nil, err
    }

    result := make([]*UserItem, 0, len(rows))
    for _, row := range rows {
        result = append(result, fromUser(row))
    }

    return result, nil
}

// RevokeUserSessions 校验 32 位用户 ID 后撤销全部会话，布尔值表示操作成功。
func (r *mutationResolver) RevokeUserSessions(ctx context.Context, userID string) (bool, error) {
    if err := r.usersReady(); err != nil {
        return false, err
    }

    id, err := strconv.Atoi(userID)
    if err != nil || id <= 0 || id > 2147483647 {
        return false, &httperr.Error{Code: "BAD_USER_INPUT", Message: "用户 ID 需要有效的正整数"}
    }

    err = r.Users.RevokeUserSessions(ctx, id)
    return err == nil, err
}

// RevokeUserSession 分别校验用户与会话 ID，由认证服务复核权限并执行幂等撤销。
func (r *mutationResolver) RevokeUserSession(ctx context.Context, userID string, sessionID string) (bool, error) {
    if err := r.usersReady(); err != nil {
        return false, err
    }

    uid, err := sessionManagementID(userID)
    if err != nil {
        return false, err
    }

    sid, err := sessionManagementID(sessionID)
    if err != nil {
        return false, err
    }

    err = r.Users.RevokeUserSession(ctx, uid, sid)
    return err == nil, err
}

// CreateShop 在认证服务存在时检查 shop:create，再调用共享业务服务创建店铺。
func (r *mutationResolver) CreateShop(ctx context.Context, set CreateShopSetInput) (*model.ShopItem, error) {
    if r.Users != nil {
        if err := r.Users.Require(ctx, "shop", "create"); err != nil {
            return nil, err
        }
    }

    row, err := r.Shops.Create(ctx, service.Create{Name: set.Name, Slug: set.Slug, Status: set.Status})
    return model.FromShop(row), err
}

// GetCurrentUser 读取当前已认证用户并映射为后台安全 DTO。
func (r *queryResolver) GetCurrentUser(ctx context.Context) (*UserItem, error) {
    if err := r.usersReady(); err != nil {
        return nil, err
    }

    row, err := r.Users.CurrentUser(ctx)
    return fromUser(row), err
}

// GetCurrentPermissions 返回当前身份的角色权限及应用菜单别名，缺少身份时返回权限错误。
func (r *queryResolver) GetCurrentPermissions(ctx context.Context) ([]string, error) {
    if err := r.usersReady(); err != nil {
        return nil, err
    }

    user, ok := auth.UserFrom(ctx)
    if !ok {
        return nil, &httperr.Error{Code: "FORBIDDEN", Message: "当前会话缺少身份信息"}
    }
    return r.Users.DashboardPermissions(user), nil
}

// GetUser 映射筛选并调用带权限和审计的用户查询服务。
func (r *queryResolver) GetUser(ctx context.Context, where UserFilters) (*UserItem, error) {
    if err := r.usersReady(); err != nil {
        return nil, err
    }

    row, err := r.Users.GetUser(ctx, userFilters(&where))
    return fromUser(row), err
}

// ListUsers 保留可选分页参数，转换稳定排序和筛选后返回用户 DTO 列表。
func (r *queryResolver) ListUsers(ctx context.Context, limit *int, offset *int, orderBy *UserOrderBy, where *UserFilters) ([]*UserItem, error) {
    if err := r.usersReady(); err != nil {
        return nil, err
    }

    input := auth.UserListQuery{Limit: 20, Where: userFilters(where)}
    if limit != nil {
        input.Limit = *limit
    }
    if offset != nil {
        input.Offset = *offset
    }

    orders, err := userOrders(orderBy)
    if err != nil {
        return nil, err
    }

    input.Order = orders
    rows, err := r.Users.ListUsers(ctx, input)
    if err != nil {
        return nil, err
    }

    result := make([]*UserItem, 0, len(rows))
    for _, row := range rows {
        result = append(result, fromUser(row))
    }

    return result, nil
}

// ListUserSessions 校验用户 ID 和分页，将有效会话的安全投影及当前会话标记映射到 Schema。
func (r *queryResolver) ListUserSessions(ctx context.Context, userID string, limit *int, offset *int) ([]*UserSessionItem, error) {
    if err := r.usersReady(); err != nil {
        return nil, err
    }

    uid, err := sessionManagementID(userID)
    if err != nil {
        return nil, err
    }

    size, start := 20, 0
    if limit != nil {
        size = *limit
        if size == 0 {
            return nil, &httperr.Error{Code: "BAD_USER_INPUT", Message: "每页数量需要正整数"}
        }
    }
    if offset != nil {
        start = *offset
    }

    rows, err := r.Users.ListUserSessions(ctx, uid, size, start)
    if err != nil {
        return nil, err
    }

    result := make([]*UserSessionItem, 0, len(rows))
    for _, row := range rows {
        result = append(result, &UserSessionItem{
            ID:        strconv.Itoa(row.ID),
            UserID:    strconv.Itoa(row.UserID),
            IPAddress: row.IPAddress,
            UserAgent: row.UserAgent,
            CreatedAt: scalar.DateTime(row.CreatedAt),
            UpdatedAt: scalar.DateTime(row.UpdatedAt),
            ExpiresAt: scalar.DateTime(row.ExpiresAt),
            Current:   row.Current,
        })
    }

    return result, nil
}

// GetShop 在认证服务存在时检查 shop:list，转换 eq 条件后读取店铺。
func (r *queryResolver) GetShop(ctx context.Context, where model.ShopFilters) (*model.ShopItem, error) {
    if r.Users != nil {
        if err := r.Users.Require(ctx, "shop", "list"); err != nil {
            return nil, err
        }
    }

    lookup, err := where.Lookup()
    if err != nil {
        return nil, err
    }

    row, err := r.Shops.Get(ctx, lookup)
    return model.FromShop(row), err
}

// ListShops 转换可选筛选、分页及按优先级稳定收集的排序，存储层补齐唯一 ID 排序。
func (r *queryResolver) ListShops(ctx context.Context, limit *int, offset *int, orderBy *ShopOrderBy, where *model.ShopFilters) ([]*model.ShopItem, error) {
    if r.Users != nil {
        if err := r.Users.Require(ctx, "shop", "list"); err != nil {
            return nil, err
        }
    }

    input := service.ListQuery{Limit: 20}
    if limit != nil {
        input.Limit = *limit
    }
    if offset != nil {
        input.Offset = *offset
    }
    if where != nil {
        var err error
        input.Where, input.SlugLike, err = where.ListLookup()
        if err != nil {
            return nil, err
        }
    }
    if orderBy != nil {
        type ordered struct {
            order    service.ShopOrder
            priority int
        }
        orders := []ordered{}
        for _, entry := range []struct {
            field string
            value *InnerOrder
        }{
            {"createdAt", orderBy.CreatedAt}, {"id", orderBy.ID}, {"name", orderBy.Name},
            {"slug", orderBy.Slug}, {"status", orderBy.Status}, {"updatedAt", orderBy.UpdatedAt},
        } {
            if entry.value == nil {
                continue
            }
            if entry.value.Priority < 1 {
                return nil, &service.Error{Code: "BAD_USER_INPUT", Message: "排序 priority 需要大于等于 1"}
            }

            orders = append(orders, ordered{service.ShopOrder{Field: entry.field, Desc: entry.value.Direction == OrderDirectionDesc}, entry.value.Priority})
        }

        slices.SortStableFunc(orders, func(a, b ordered) int { return cmp.Compare(a.priority, b.priority) })
        for _, item := range orders {
            input.Order = append(input.Order, item.order)
        }
    }

    rows, err := r.Shops.List(ctx, input)
    if err != nil {
        return nil, err
    }

    result := make([]*model.ShopItem, 0, len(rows))
    for _, row := range rows {
        result = append(result, model.FromShop(row))
    }

    return result, nil
}

// Mutation 提供后台 Schema 的写操作实现。
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query 提供后台 Schema 的查询实现。
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
    mutationResolver struct{ *Resolver }

    queryResolver struct{ *Resolver }
)
