// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package admin

import (
    "bytes"
    "fmt"
    "io"
    "strconv"

    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/packages/go-server-kit/modules/queue"
    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/projects/multi-database-demo/internal/graph/model"
    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/projects/multi-database-demo/internal/graph/scalar"
    "github.com/99designs/gqlgen/graphql"
)

type CreateShopSetInput struct {
    Name   string  `json:"name"`
    Slug   string  `json:"slug"`
    Status *string `json:"status,omitempty"`
}

type CreateUserSetInput struct {
    Email    string  `json:"email"`
    Name     string  `json:"name"`
    Password string  `json:"password"`
    Role     *string `json:"role,omitempty"`
}

type InnerOrder struct {
    Direction OrderDirection `json:"direction"`
    Priority  int            `json:"priority"`
}

type Mutation struct {
}

type Query struct {
}

type QueueExecutionRecordSetInput struct {
    RecordID   string  `json:"recordId"`
    StatusHint *string `json:"statusHint,omitempty"`
}

type QueueExecutionRecordUpdatePayload struct {
    Detail        *queue.Record `json:"detail"`
    NoticeMessage string        `json:"noticeMessage"`
}

type ShopOrderBy struct {
    CreatedAt *InnerOrder `json:"createdAt,omitempty"`
    ID        *InnerOrder `json:"id,omitempty"`
    Name      *InnerOrder `json:"name,omitempty"`
    Slug      *InnerOrder `json:"slug,omitempty"`
    Status    *InnerOrder `json:"status,omitempty"`
    UpdatedAt *InnerOrder `json:"updatedAt,omitempty"`
}

type UpdateUserSetInput struct {
    BanExpires graphql.Omittable[*scalar.DateTime] `json:"banExpires,omitempty"`
    BanReason  graphql.Omittable[*string]          `json:"banReason,omitempty"`
    Banned     *bool                               `json:"banned,omitempty"`
    Name       *string                             `json:"name,omitempty"`
    Role       *string                             `json:"role,omitempty"`
}

type UserFilters struct {
    Banned        *bool                `json:"banned,omitempty"`
    Email         *model.StringFilters `json:"email,omitempty"`
    EmailVerified *bool                `json:"emailVerified,omitempty"`
    ID            *model.IntFilters    `json:"id,omitempty"`
    Role          *model.StringFilters `json:"role,omitempty"`
}

type UserItem struct {
    BanExpires    *scalar.DateTime `json:"banExpires,omitempty"`
    BanReason     *string          `json:"banReason,omitempty"`
    Banned        *bool            `json:"banned,omitempty"`
    CreatedAt     *scalar.DateTime `json:"createdAt,omitempty"`
    Email         *string          `json:"email,omitempty"`
    EmailVerified *bool            `json:"emailVerified,omitempty"`
    ID            *string          `json:"id,omitempty"`
    Image         *string          `json:"image,omitempty"`
    Name          *string          `json:"name,omitempty"`
    Role          *string          `json:"role,omitempty"`
    UpdatedAt     *scalar.DateTime `json:"updatedAt,omitempty"`
}

type UserOrderBy struct {
    CreatedAt *InnerOrder `json:"createdAt,omitempty"`
    Email     *InnerOrder `json:"email,omitempty"`
    ID        *InnerOrder `json:"id,omitempty"`
    Name      *InnerOrder `json:"name,omitempty"`
    Role      *InnerOrder `json:"role,omitempty"`
    UpdatedAt *InnerOrder `json:"updatedAt,omitempty"`
}

type UserSessionItem struct {
    ID        string          `json:"id"`
    UserID    string          `json:"userId"`
    IPAddress *string         `json:"ipAddress,omitempty"`
    UserAgent *string         `json:"userAgent,omitempty"`
    CreatedAt scalar.DateTime `json:"createdAt"`
    UpdatedAt scalar.DateTime `json:"updatedAt"`
    ExpiresAt scalar.DateTime `json:"expiresAt"`
    Current   bool            `json:"current"`
}

type OrderDirection string

const (
    OrderDirectionAsc  OrderDirection = "asc"
    OrderDirectionDesc OrderDirection = "desc"
)

var AllOrderDirection = []OrderDirection{
    OrderDirectionAsc,
    OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
    switch e {
    case OrderDirectionAsc, OrderDirectionDesc:
        return true
    }
    return false
}

func (e OrderDirection) String() string {
    return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
    str, ok := v.(string)
    if !ok {
        return fmt.Errorf("enums must be strings")
    }

    *e = OrderDirection(str)
    if !e.IsValid() {
        return fmt.Errorf("%s is not a valid OrderDirection", str)
    }
    return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
    _, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
    s, err := strconv.Unquote(string(b))
    if err != nil {
        return err
    }
    return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
    var buf bytes.Buffer
    e.MarshalGQL(&buf)
    return buf.Bytes(), nil
}
