package admin

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
    "context"
    "strconv"

    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/packages/go-server-kit/infra/schedule"
    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/packages/go-server-kit/modules/queue"
    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/packages/go-server-kit/transport/httperr"
)

// UpdateQueueExecutionRecord 复核 queue:read/retry 并传递操作人身份，返回安排重试的详情和提示。
func (r *mutationResolver) UpdateQueueExecutionRecord(ctx context.Context, set QueueExecutionRecordSetInput) (*QueueExecutionRecordUpdatePayload, error) {
    actor, err := r.queueActor(ctx, "read", "retry")
    if err != nil {
        return nil, err
    }

    detail, err := r.Queue.Retry(ctx, set.RecordID, strconv.Itoa(actor.ID), actor.Name)
    if err != nil {
        return nil, err
    }
    return &QueueExecutionRecordUpdatePayload{Detail: detail, NoticeMessage: "已安排重试"}, nil
}

// GetQueueDashboard 复核 queue:read 后返回队列状态与消费进程概览。
func (r *queryResolver) GetQueueDashboard(ctx context.Context) (*queue.DashboardPayload, error) {
    if _, err := r.queueActor(ctx, "read"); err != nil {
        return nil, err
    }
    return r.Queue.Dashboard(ctx)
}

// GetQueueSchedules 仅向具备队列查看权限的有效账号提供调度观测。
func (r *queryResolver) GetQueueSchedules(ctx context.Context) (*schedule.Payload, error) {
    if _, err := r.queueActor(ctx, "read"); err != nil {
        return nil, err
    }
    return r.Queue.Schedules(ctx)
}

// GetQueueExecutionRecord 读取安全历史详情；操作人缺少 retry 权限时关闭详情中的重试能力。
func (r *queryResolver) GetQueueExecutionRecord(ctx context.Context, recordID string, statusHint *string) (*queue.Record, error) {
    actor, err := r.queueActor(ctx, "read")
    if err != nil {
        return nil, err
    }

    record, err := r.Queue.Get(ctx, recordID)
    if err == nil && !r.Users.Allows(actor, "queue", "retry") {
        record.CanRetry = false
        record.RetryDisabledReason = "当前账号缺少重试权限"
    }
    return record, err
}

// ListQueueExecutionRecords 复核读取权限并映射可选筛选，显式零分页大小返回输入错误。
func (r *queryResolver) ListQueueExecutionRecords(ctx context.Context, status string, limit *int, offset *int, orderBy *string, orderDirection *string, queueName *string, jobName *string, from *float64, to *float64) (*queue.RecordsPayload, error) {
    if _, err := r.queueActor(ctx, "read"); err != nil {
        return nil, err
    }

    query := queue.ListQuery{Status: status, From: from, To: to}
    if orderBy != nil {
        query.OrderBy = *orderBy
    }
    if orderDirection != nil {
        query.OrderDirection = *orderDirection
    }
    if limit != nil {
        if *limit == 0 {
            return nil, &httperr.Error{Code: "BAD_USER_INPUT", Message: "每页数量支持 20、50、100"}
        }

        query.Limit = *limit
    }
    if offset != nil {
        query.Offset = *offset
    }
    if queueName != nil {
        query.QueueName = *queueName
    }
    if jobName != nil {
        query.JobName = *jobName
    }
    return r.Queue.List(ctx, query)
}
