// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
    "context"
    "database/sql"

    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/packages/go-server-kit/modules/auth"
    "gorm.io/gorm"
    "gorm.io/gorm/clause"
    "gorm.io/gorm/schema"

    "gorm.io/gen"
    "gorm.io/gen/field"

    "gorm.io/plugin/dbresolver"
)

func newBootstrap(db *gorm.DB, opts ...gen.DOOption) bootstrap {
    _bootstrap := bootstrap{}

    _bootstrap.bootstrapDo.UseDB(db, opts...)
    _bootstrap.bootstrapDo.UseModel(&auth.Bootstrap{})

    tableName := _bootstrap.bootstrapDo.TableName()
    _bootstrap.ALL = field.NewAsterisk(tableName)
    _bootstrap.ID = field.NewInt(tableName, "id")
    _bootstrap.Revision = field.NewInt(tableName, "revision")

    _bootstrap.fillFieldMap()

    return _bootstrap
}

type bootstrap struct {
    bootstrapDo bootstrapDo

    ALL      field.Asterisk
    ID       field.Int
    Revision field.Int

    fieldMap map[string]field.Expr
}

func (b bootstrap) Table(newTableName string) *bootstrap {
    b.bootstrapDo.UseTable(newTableName)
    return b.updateTableName(newTableName)
}

func (b bootstrap) As(alias string) *bootstrap {
    b.bootstrapDo.DO = *(b.bootstrapDo.As(alias).(*gen.DO))
    return b.updateTableName(alias)
}

func (b *bootstrap) updateTableName(table string) *bootstrap {
    b.ALL = field.NewAsterisk(table)
    b.ID = field.NewInt(table, "id")
    b.Revision = field.NewInt(table, "revision")

    b.fillFieldMap()

    return b
}

func (b *bootstrap) WithContext(ctx context.Context) IBootstrapDo {
    return b.bootstrapDo.WithContext(ctx)
}

func (b bootstrap) TableName() string { return b.bootstrapDo.TableName() }

func (b bootstrap) Alias() string { return b.bootstrapDo.Alias() }

func (b bootstrap) Columns(cols ...field.Expr) gen.Columns { return b.bootstrapDo.Columns(cols...) }

func (b *bootstrap) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
    _f, ok := b.fieldMap[fieldName]
    if !ok || _f == nil {
        return nil, false
    }
    _oe, ok := _f.(field.OrderExpr)
    return _oe, ok
}

func (b *bootstrap) fillFieldMap() {
    b.fieldMap = make(map[string]field.Expr, 2)
    b.fieldMap["id"] = b.ID
    b.fieldMap["revision"] = b.Revision
}

func (b bootstrap) clone(db *gorm.DB) bootstrap {
    b.bootstrapDo.ReplaceConnPool(db.Statement.ConnPool)
    return b
}

func (b bootstrap) replaceDB(db *gorm.DB) bootstrap {
    b.bootstrapDo.ReplaceDB(db)
    return b
}

type bootstrapDo struct{ gen.DO }

type IBootstrapDo interface {
    gen.SubQuery
    Debug() IBootstrapDo
    WithContext(ctx context.Context) IBootstrapDo
    WithResult(fc func(tx gen.Dao)) gen.ResultInfo
    ReplaceDB(db *gorm.DB)
    ReadDB() IBootstrapDo
    WriteDB() IBootstrapDo
    As(alias string) gen.Dao
    Session(config *gorm.Session) IBootstrapDo
    Columns(cols ...field.Expr) gen.Columns
    Clauses(conds ...clause.Expression) IBootstrapDo
    Not(conds ...gen.Condition) IBootstrapDo
    Or(conds ...gen.Condition) IBootstrapDo
    Select(conds ...field.Expr) IBootstrapDo
    Where(conds ...gen.Condition) IBootstrapDo
    Order(conds ...field.Expr) IBootstrapDo
    Distinct(cols ...field.Expr) IBootstrapDo
    Omit(cols ...field.Expr) IBootstrapDo
    Join(table schema.Tabler, on ...field.Expr) IBootstrapDo
    LeftJoin(table schema.Tabler, on ...field.Expr) IBootstrapDo
    RightJoin(table schema.Tabler, on ...field.Expr) IBootstrapDo
    Group(cols ...field.Expr) IBootstrapDo
    Having(conds ...gen.Condition) IBootstrapDo
    Limit(limit int) IBootstrapDo
    Offset(offset int) IBootstrapDo
    Count() (count int64, err error)
    Scopes(funcs ...func(gen.Dao) gen.Dao) IBootstrapDo
    Unscoped() IBootstrapDo
    Create(values ...*auth.Bootstrap) error
    CreateInBatches(values []*auth.Bootstrap, batchSize int) error
    Save(values ...*auth.Bootstrap) error
    First() (*auth.Bootstrap, error)
    Take() (*auth.Bootstrap, error)
    Last() (*auth.Bootstrap, error)
    Find() ([]*auth.Bootstrap, error)
    FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*auth.Bootstrap, err error)
    FindInBatches(result *[]*auth.Bootstrap, batchSize int, fc func(tx gen.Dao, batch int) error) error
    Pluck(column field.Expr, dest interface{}) error
    Delete(...*auth.Bootstrap) (info gen.ResultInfo, err error)
    Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
    UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
    Updates(value interface{}) (info gen.ResultInfo, err error)
    UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
    UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
    UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
    UpdateFrom(q gen.SubQuery) gen.Dao
    Attrs(attrs ...field.AssignExpr) IBootstrapDo
    Assign(attrs ...field.AssignExpr) IBootstrapDo
    Joins(fields ...field.RelationField) IBootstrapDo
    Preload(fields ...field.RelationField) IBootstrapDo
    FirstOrInit() (*auth.Bootstrap, error)
    FirstOrCreate() (*auth.Bootstrap, error)
    FindByPage(offset int, limit int) (result []*auth.Bootstrap, count int64, err error)
    ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
    Rows() (*sql.Rows, error)
    Row() *sql.Row
    Scan(result interface{}) (err error)
    Returning(value interface{}, columns ...string) IBootstrapDo
    UnderlyingDB() *gorm.DB
    schema.Tabler
}

func (b bootstrapDo) Debug() IBootstrapDo {
    return b.withDO(b.DO.Debug())
}

func (b bootstrapDo) WithContext(ctx context.Context) IBootstrapDo {
    return b.withDO(b.DO.WithContext(ctx))
}

func (b bootstrapDo) ReadDB() IBootstrapDo {
    return b.Clauses(dbresolver.Read)
}

func (b bootstrapDo) WriteDB() IBootstrapDo {
    return b.Clauses(dbresolver.Write)
}

func (b bootstrapDo) Session(config *gorm.Session) IBootstrapDo {
    return b.withDO(b.DO.Session(config))
}

func (b bootstrapDo) Clauses(conds ...clause.Expression) IBootstrapDo {
    return b.withDO(b.DO.Clauses(conds...))
}

func (b bootstrapDo) Returning(value interface{}, columns ...string) IBootstrapDo {
    return b.withDO(b.DO.Returning(value, columns...))
}

func (b bootstrapDo) Not(conds ...gen.Condition) IBootstrapDo {
    return b.withDO(b.DO.Not(conds...))
}

func (b bootstrapDo) Or(conds ...gen.Condition) IBootstrapDo {
    return b.withDO(b.DO.Or(conds...))
}

func (b bootstrapDo) Select(conds ...field.Expr) IBootstrapDo {
    return b.withDO(b.DO.Select(conds...))
}

func (b bootstrapDo) Where(conds ...gen.Condition) IBootstrapDo {
    return b.withDO(b.DO.Where(conds...))
}

func (b bootstrapDo) Order(conds ...field.Expr) IBootstrapDo {
    return b.withDO(b.DO.Order(conds...))
}

func (b bootstrapDo) Distinct(cols ...field.Expr) IBootstrapDo {
    return b.withDO(b.DO.Distinct(cols...))
}

func (b bootstrapDo) Omit(cols ...field.Expr) IBootstrapDo {
    return b.withDO(b.DO.Omit(cols...))
}

func (b bootstrapDo) Join(table schema.Tabler, on ...field.Expr) IBootstrapDo {
    return b.withDO(b.DO.Join(table, on...))
}

func (b bootstrapDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBootstrapDo {
    return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bootstrapDo) RightJoin(table schema.Tabler, on ...field.Expr) IBootstrapDo {
    return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bootstrapDo) Group(cols ...field.Expr) IBootstrapDo {
    return b.withDO(b.DO.Group(cols...))
}

func (b bootstrapDo) Having(conds ...gen.Condition) IBootstrapDo {
    return b.withDO(b.DO.Having(conds...))
}

func (b bootstrapDo) Limit(limit int) IBootstrapDo {
    return b.withDO(b.DO.Limit(limit))
}

func (b bootstrapDo) Offset(offset int) IBootstrapDo {
    return b.withDO(b.DO.Offset(offset))
}

func (b bootstrapDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBootstrapDo {
    return b.withDO(b.DO.Scopes(funcs...))
}

func (b bootstrapDo) Unscoped() IBootstrapDo {
    return b.withDO(b.DO.Unscoped())
}

func (b bootstrapDo) Create(values ...*auth.Bootstrap) error {
    if len(values) == 0 {
        return nil
    }
    return b.DO.Create(values)
}

func (b bootstrapDo) CreateInBatches(values []*auth.Bootstrap, batchSize int) error {
    return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bootstrapDo) Save(values ...*auth.Bootstrap) error {
    if len(values) == 0 {
        return nil
    }
    return b.DO.Save(values)
}

func (b bootstrapDo) First() (*auth.Bootstrap, error) {
    if result, err := b.DO.First(); err != nil {
        return nil, err
    } else {
        return result.(*auth.Bootstrap), nil
    }
}

func (b bootstrapDo) Take() (*auth.Bootstrap, error) {
    if result, err := b.DO.Take(); err != nil {
        return nil, err
    } else {
        return result.(*auth.Bootstrap), nil
    }
}

func (b bootstrapDo) Last() (*auth.Bootstrap, error) {
    if result, err := b.DO.Last(); err != nil {
        return nil, err
    } else {
        return result.(*auth.Bootstrap), nil
    }
}

func (b bootstrapDo) Find() ([]*auth.Bootstrap, error) {
    result, err := b.DO.Find()
    return result.([]*auth.Bootstrap), err
}

func (b bootstrapDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*auth.Bootstrap, err error) {
    buf := make([]*auth.Bootstrap, 0, batchSize)
    err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
        defer func() { results = append(results, buf...) }()
        return fc(tx, batch)
    })
    return results, err
}

func (b bootstrapDo) FindInBatches(result *[]*auth.Bootstrap, batchSize int, fc func(tx gen.Dao, batch int) error) error {
    return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bootstrapDo) Attrs(attrs ...field.AssignExpr) IBootstrapDo {
    return b.withDO(b.DO.Attrs(attrs...))
}

func (b bootstrapDo) Assign(attrs ...field.AssignExpr) IBootstrapDo {
    return b.withDO(b.DO.Assign(attrs...))
}

func (b bootstrapDo) Joins(fields ...field.RelationField) IBootstrapDo {
    for _, _f := range fields {
        b = *b.withDO(b.DO.Joins(_f))
    }
    return &b
}

func (b bootstrapDo) Preload(fields ...field.RelationField) IBootstrapDo {
    for _, _f := range fields {
        b = *b.withDO(b.DO.Preload(_f))
    }
    return &b
}

func (b bootstrapDo) FirstOrInit() (*auth.Bootstrap, error) {
    if result, err := b.DO.FirstOrInit(); err != nil {
        return nil, err
    } else {
        return result.(*auth.Bootstrap), nil
    }
}

func (b bootstrapDo) FirstOrCreate() (*auth.Bootstrap, error) {
    if result, err := b.DO.FirstOrCreate(); err != nil {
        return nil, err
    } else {
        return result.(*auth.Bootstrap), nil
    }
}

func (b bootstrapDo) FindByPage(offset int, limit int) (result []*auth.Bootstrap, count int64, err error) {
    result, err = b.Offset(offset).Limit(limit).Find()
    if err != nil {
        return
    }

    if size := len(result); 0 < limit && 0 < size && size < limit {
        count = int64(size + offset)
        return
    }

    count, err = b.Offset(-1).Limit(-1).Count()
    return
}

func (b bootstrapDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
    count, err = b.Count()
    if err != nil {
        return
    }

    err = b.Offset(offset).Limit(limit).Scan(result)
    return
}

func (b bootstrapDo) Scan(result interface{}) (err error) {
    return b.DO.Scan(result)
}

func (b bootstrapDo) Delete(models ...*auth.Bootstrap) (result gen.ResultInfo, err error) {
    return b.DO.Delete(models)
}

func (b *bootstrapDo) withDO(do gen.Dao) *bootstrapDo {
    b.DO = *do.(*gen.DO)
    return b
}
