// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
    "context"
    "database/sql"

    "gorm.io/gorm"

    "gorm.io/gen"

    "gorm.io/plugin/dbresolver"
)

var (
    Q            = new(Query)
    Account      *account
    Bootstrap    *bootstrap
    Session      *session
    Shop         *shop
    User         *user
    Verification *verification
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
    *Q = *Use(db, opts...)
    Account = &Q.Account
    Bootstrap = &Q.Bootstrap
    Session = &Q.Session
    Shop = &Q.Shop
    User = &Q.User
    Verification = &Q.Verification
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
    return &Query{
        db:           db,
        Account:      newAccount(db, opts...),
        Bootstrap:    newBootstrap(db, opts...),
        Session:      newSession(db, opts...),
        Shop:         newShop(db, opts...),
        User:         newUser(db, opts...),
        Verification: newVerification(db, opts...),
    }
}

type Query struct {
    db  *gorm.DB

    Account      account
    Bootstrap    bootstrap
    Session      session
    Shop         shop
    User         user
    Verification verification
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
    return &Query{
        db:           db,
        Account:      q.Account.clone(db),
        Bootstrap:    q.Bootstrap.clone(db),
        Session:      q.Session.clone(db),
        Shop:         q.Shop.clone(db),
        User:         q.User.clone(db),
        Verification: q.Verification.clone(db),
    }
}

func (q *Query) ReadDB() *Query {
    return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
    return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
    return &Query{
        db:           db,
        Account:      q.Account.replaceDB(db),
        Bootstrap:    q.Bootstrap.replaceDB(db),
        Session:      q.Session.replaceDB(db),
        Shop:         q.Shop.replaceDB(db),
        User:         q.User.replaceDB(db),
        Verification: q.Verification.replaceDB(db),
    }
}

type queryCtx struct {
    Account      IAccountDo
    Bootstrap    IBootstrapDo
    Session      ISessionDo
    Shop         IShopDo
    User         IUserDo
    Verification IVerificationDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
    return &queryCtx{
        Account:      q.Account.WithContext(ctx),
        Bootstrap:    q.Bootstrap.WithContext(ctx),
        Session:      q.Session.WithContext(ctx),
        Shop:         q.Shop.WithContext(ctx),
        User:         q.User.WithContext(ctx),
        Verification: q.Verification.WithContext(ctx),
    }
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
    return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
    tx := q.db.Begin(opts...)
    return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
    *Query
    Error error
}

func (q *QueryTx) Commit() error {
    return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
    return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
    return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
    return q.db.RollbackTo(name).Error
}
