// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
    "context"
    "database/sql"

    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/packages/go-server-kit/modules/auth"
    "gorm.io/gorm"
    "gorm.io/gorm/clause"
    "gorm.io/gorm/schema"

    "gorm.io/gen"
    "gorm.io/gen/field"

    "gorm.io/plugin/dbresolver"
)

func newVerification(db *gorm.DB, opts ...gen.DOOption) verification {
    _verification := verification{}

    _verification.verificationDo.UseDB(db, opts...)
    _verification.verificationDo.UseModel(&auth.Verification{})

    tableName := _verification.verificationDo.TableName()
    _verification.ALL = field.NewAsterisk(tableName)
    _verification.ID = field.NewInt(tableName, "id")
    _verification.Identifier = field.NewString(tableName, "identifier")
    _verification.Value = field.NewString(tableName, "value")
    _verification.ExpiresAt = field.NewTime(tableName, "expires_at")
    _verification.CreatedAt = field.NewTime(tableName, "created_at")
    _verification.UpdatedAt = field.NewTime(tableName, "updated_at")

    _verification.fillFieldMap()

    return _verification
}

type verification struct {
    verificationDo verificationDo

    ALL        field.Asterisk
    ID         field.Int
    Identifier field.String
    Value      field.String
    ExpiresAt  field.Time
    CreatedAt  field.Time
    UpdatedAt  field.Time

    fieldMap map[string]field.Expr
}

func (v verification) Table(newTableName string) *verification {
    v.verificationDo.UseTable(newTableName)
    return v.updateTableName(newTableName)
}

func (v verification) As(alias string) *verification {
    v.verificationDo.DO = *(v.verificationDo.As(alias).(*gen.DO))
    return v.updateTableName(alias)
}

func (v *verification) updateTableName(table string) *verification {
    v.ALL = field.NewAsterisk(table)
    v.ID = field.NewInt(table, "id")
    v.Identifier = field.NewString(table, "identifier")
    v.Value = field.NewString(table, "value")
    v.ExpiresAt = field.NewTime(table, "expires_at")
    v.CreatedAt = field.NewTime(table, "created_at")
    v.UpdatedAt = field.NewTime(table, "updated_at")

    v.fillFieldMap()

    return v
}

func (v *verification) WithContext(ctx context.Context) IVerificationDo {
    return v.verificationDo.WithContext(ctx)
}

func (v verification) TableName() string { return v.verificationDo.TableName() }

func (v verification) Alias() string { return v.verificationDo.Alias() }

func (v verification) Columns(cols ...field.Expr) gen.Columns {
    return v.verificationDo.Columns(cols...)
}

func (v *verification) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
    _f, ok := v.fieldMap[fieldName]
    if !ok || _f == nil {
        return nil, false
    }
    _oe, ok := _f.(field.OrderExpr)
    return _oe, ok
}

func (v *verification) fillFieldMap() {
    v.fieldMap = make(map[string]field.Expr, 6)
    v.fieldMap["id"] = v.ID
    v.fieldMap["identifier"] = v.Identifier
    v.fieldMap["value"] = v.Value
    v.fieldMap["expires_at"] = v.ExpiresAt
    v.fieldMap["created_at"] = v.CreatedAt
    v.fieldMap["updated_at"] = v.UpdatedAt
}

func (v verification) clone(db *gorm.DB) verification {
    v.verificationDo.ReplaceConnPool(db.Statement.ConnPool)
    return v
}

func (v verification) replaceDB(db *gorm.DB) verification {
    v.verificationDo.ReplaceDB(db)
    return v
}

type verificationDo struct{ gen.DO }

type IVerificationDo interface {
    gen.SubQuery
    Debug() IVerificationDo
    WithContext(ctx context.Context) IVerificationDo
    WithResult(fc func(tx gen.Dao)) gen.ResultInfo
    ReplaceDB(db *gorm.DB)
    ReadDB() IVerificationDo
    WriteDB() IVerificationDo
    As(alias string) gen.Dao
    Session(config *gorm.Session) IVerificationDo
    Columns(cols ...field.Expr) gen.Columns
    Clauses(conds ...clause.Expression) IVerificationDo
    Not(conds ...gen.Condition) IVerificationDo
    Or(conds ...gen.Condition) IVerificationDo
    Select(conds ...field.Expr) IVerificationDo
    Where(conds ...gen.Condition) IVerificationDo
    Order(conds ...field.Expr) IVerificationDo
    Distinct(cols ...field.Expr) IVerificationDo
    Omit(cols ...field.Expr) IVerificationDo
    Join(table schema.Tabler, on ...field.Expr) IVerificationDo
    LeftJoin(table schema.Tabler, on ...field.Expr) IVerificationDo
    RightJoin(table schema.Tabler, on ...field.Expr) IVerificationDo
    Group(cols ...field.Expr) IVerificationDo
    Having(conds ...gen.Condition) IVerificationDo
    Limit(limit int) IVerificationDo
    Offset(offset int) IVerificationDo
    Count() (count int64, err error)
    Scopes(funcs ...func(gen.Dao) gen.Dao) IVerificationDo
    Unscoped() IVerificationDo
    Create(values ...*auth.Verification) error
    CreateInBatches(values []*auth.Verification, batchSize int) error
    Save(values ...*auth.Verification) error
    First() (*auth.Verification, error)
    Take() (*auth.Verification, error)
    Last() (*auth.Verification, error)
    Find() ([]*auth.Verification, error)
    FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*auth.Verification, err error)
    FindInBatches(result *[]*auth.Verification, batchSize int, fc func(tx gen.Dao, batch int) error) error
    Pluck(column field.Expr, dest interface{}) error
    Delete(...*auth.Verification) (info gen.ResultInfo, err error)
    Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
    UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
    Updates(value interface{}) (info gen.ResultInfo, err error)
    UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
    UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
    UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
    UpdateFrom(q gen.SubQuery) gen.Dao
    Attrs(attrs ...field.AssignExpr) IVerificationDo
    Assign(attrs ...field.AssignExpr) IVerificationDo
    Joins(fields ...field.RelationField) IVerificationDo
    Preload(fields ...field.RelationField) IVerificationDo
    FirstOrInit() (*auth.Verification, error)
    FirstOrCreate() (*auth.Verification, error)
    FindByPage(offset int, limit int) (result []*auth.Verification, count int64, err error)
    ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
    Rows() (*sql.Rows, error)
    Row() *sql.Row
    Scan(result interface{}) (err error)
    Returning(value interface{}, columns ...string) IVerificationDo
    UnderlyingDB() *gorm.DB
    schema.Tabler
}

func (v verificationDo) Debug() IVerificationDo {
    return v.withDO(v.DO.Debug())
}

func (v verificationDo) WithContext(ctx context.Context) IVerificationDo {
    return v.withDO(v.DO.WithContext(ctx))
}

func (v verificationDo) ReadDB() IVerificationDo {
    return v.Clauses(dbresolver.Read)
}

func (v verificationDo) WriteDB() IVerificationDo {
    return v.Clauses(dbresolver.Write)
}

func (v verificationDo) Session(config *gorm.Session) IVerificationDo {
    return v.withDO(v.DO.Session(config))
}

func (v verificationDo) Clauses(conds ...clause.Expression) IVerificationDo {
    return v.withDO(v.DO.Clauses(conds...))
}

func (v verificationDo) Returning(value interface{}, columns ...string) IVerificationDo {
    return v.withDO(v.DO.Returning(value, columns...))
}

func (v verificationDo) Not(conds ...gen.Condition) IVerificationDo {
    return v.withDO(v.DO.Not(conds...))
}

func (v verificationDo) Or(conds ...gen.Condition) IVerificationDo {
    return v.withDO(v.DO.Or(conds...))
}

func (v verificationDo) Select(conds ...field.Expr) IVerificationDo {
    return v.withDO(v.DO.Select(conds...))
}

func (v verificationDo) Where(conds ...gen.Condition) IVerificationDo {
    return v.withDO(v.DO.Where(conds...))
}

func (v verificationDo) Order(conds ...field.Expr) IVerificationDo {
    return v.withDO(v.DO.Order(conds...))
}

func (v verificationDo) Distinct(cols ...field.Expr) IVerificationDo {
    return v.withDO(v.DO.Distinct(cols...))
}

func (v verificationDo) Omit(cols ...field.Expr) IVerificationDo {
    return v.withDO(v.DO.Omit(cols...))
}

func (v verificationDo) Join(table schema.Tabler, on ...field.Expr) IVerificationDo {
    return v.withDO(v.DO.Join(table, on...))
}

func (v verificationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVerificationDo {
    return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v verificationDo) RightJoin(table schema.Tabler, on ...field.Expr) IVerificationDo {
    return v.withDO(v.DO.RightJoin(table, on...))
}

func (v verificationDo) Group(cols ...field.Expr) IVerificationDo {
    return v.withDO(v.DO.Group(cols...))
}

func (v verificationDo) Having(conds ...gen.Condition) IVerificationDo {
    return v.withDO(v.DO.Having(conds...))
}

func (v verificationDo) Limit(limit int) IVerificationDo {
    return v.withDO(v.DO.Limit(limit))
}

func (v verificationDo) Offset(offset int) IVerificationDo {
    return v.withDO(v.DO.Offset(offset))
}

func (v verificationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVerificationDo {
    return v.withDO(v.DO.Scopes(funcs...))
}

func (v verificationDo) Unscoped() IVerificationDo {
    return v.withDO(v.DO.Unscoped())
}

func (v verificationDo) Create(values ...*auth.Verification) error {
    if len(values) == 0 {
        return nil
    }
    return v.DO.Create(values)
}

func (v verificationDo) CreateInBatches(values []*auth.Verification, batchSize int) error {
    return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v verificationDo) Save(values ...*auth.Verification) error {
    if len(values) == 0 {
        return nil
    }
    return v.DO.Save(values)
}

func (v verificationDo) First() (*auth.Verification, error) {
    if result, err := v.DO.First(); err != nil {
        return nil, err
    } else {
        return result.(*auth.Verification), nil
    }
}

func (v verificationDo) Take() (*auth.Verification, error) {
    if result, err := v.DO.Take(); err != nil {
        return nil, err
    } else {
        return result.(*auth.Verification), nil
    }
}

func (v verificationDo) Last() (*auth.Verification, error) {
    if result, err := v.DO.Last(); err != nil {
        return nil, err
    } else {
        return result.(*auth.Verification), nil
    }
}

func (v verificationDo) Find() ([]*auth.Verification, error) {
    result, err := v.DO.Find()
    return result.([]*auth.Verification), err
}

func (v verificationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*auth.Verification, err error) {
    buf := make([]*auth.Verification, 0, batchSize)
    err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
        defer func() { results = append(results, buf...) }()
        return fc(tx, batch)
    })
    return results, err
}

func (v verificationDo) FindInBatches(result *[]*auth.Verification, batchSize int, fc func(tx gen.Dao, batch int) error) error {
    return v.DO.FindInBatches(result, batchSize, fc)
}

func (v verificationDo) Attrs(attrs ...field.AssignExpr) IVerificationDo {
    return v.withDO(v.DO.Attrs(attrs...))
}

func (v verificationDo) Assign(attrs ...field.AssignExpr) IVerificationDo {
    return v.withDO(v.DO.Assign(attrs...))
}

func (v verificationDo) Joins(fields ...field.RelationField) IVerificationDo {
    for _, _f := range fields {
        v = *v.withDO(v.DO.Joins(_f))
    }
    return &v
}

func (v verificationDo) Preload(fields ...field.RelationField) IVerificationDo {
    for _, _f := range fields {
        v = *v.withDO(v.DO.Preload(_f))
    }
    return &v
}

func (v verificationDo) FirstOrInit() (*auth.Verification, error) {
    if result, err := v.DO.FirstOrInit(); err != nil {
        return nil, err
    } else {
        return result.(*auth.Verification), nil
    }
}

func (v verificationDo) FirstOrCreate() (*auth.Verification, error) {
    if result, err := v.DO.FirstOrCreate(); err != nil {
        return nil, err
    } else {
        return result.(*auth.Verification), nil
    }
}

func (v verificationDo) FindByPage(offset int, limit int) (result []*auth.Verification, count int64, err error) {
    result, err = v.Offset(offset).Limit(limit).Find()
    if err != nil {
        return
    }

    if size := len(result); 0 < limit && 0 < size && size < limit {
        count = int64(size + offset)
        return
    }

    count, err = v.Offset(-1).Limit(-1).Count()
    return
}

func (v verificationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
    count, err = v.Count()
    if err != nil {
        return
    }

    err = v.Offset(offset).Limit(limit).Scan(result)
    return
}

func (v verificationDo) Scan(result interface{}) (err error) {
    return v.DO.Scan(result)
}

func (v verificationDo) Delete(models ...*auth.Verification) (result gen.ResultInfo, err error) {
    return v.DO.Delete(models)
}

func (v *verificationDo) withDO(do gen.Dao) *verificationDo {
    v.DO = *do.(*gen.DO)
    return v
}
