package member

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
    "context"

    "codeup.aliyun.com/shanjing/labs/go-full-stack-starter.git/projects/multi-database-demo/internal/graph/model"
)

// GetShop 将成员端 eq 筛选映射到共享业务查询，空记录保留为空结果。
func (r *queryResolver) GetShop(ctx context.Context, where model.ShopFilters) (*model.ShopItem, error) {
    lookup, err := where.Lookup()
    if err != nil {
        return nil, err
    }

    row, err := r.Shops.Get(ctx, lookup)
    return model.FromShop(row), err
}

// Query 提供成员 Schema 的查询实现。
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
